apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vex-tournament
spec:
  project: default
  source:
    repoURL: 'https://github.com/Pablonara/vex_tournament-dev-fork.git'
    targetRevision: main
  destination:
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
