apiVersion: apps/v1
kind: Deployment
metadata:
  name: vex-tournament
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vex-tournament
  template:
    metadata:
      labels:
        app: vex-tournament
    spec:
      containers:
      - name: vex-tournament
        image: cocogoat1441/vex-tournament:latest
        ports:
        - containerPort: 8000
        env:
        - name: DEBUG
          value: "False"
        - name: ALLOWED_HOSTS
          value: "0.0.0.0"
        - name: STATIC_ROOT
          value: ""
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 200m
          memory: 256Mi
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
